name: auto-update-readme
on: [ push ]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3'
      - run: Rscript ./update_readme.R
