name: auto-update-readme
on: [ push ]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run update_readme script
        uses: docker://rocker/tidyverse
        run: Rscript update_readme.R
