name: Generate README

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3'

      - name: Install dependencies
        run: install.packages(c('dplyr','stringr','glue'))
        shell: Rscript {0}

      - name: Update README
        run: Rscript update_readme.R
